import "public/css/main.css";
import "public/css/all.min.css";
import Navbar from "@/components/layouts/nav/Navbar";

export const metadata = {
  title: 'Ashures Shop',
  description: 'Generated by Ashures',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="main" className="flex justify-center bg-gray-900 w-full h-screen text-white">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  )
}
